FROM node:lts-alpine

WORKDIR /app/frontend-main

COPY ../frontend-main/package*.json .
COPY ../frontend-main/vite*.js .

RUN npm install

COPY frontend-main .

# RUN npm run format

EXPOSE 5174

CMD npm run dev
